add documentation
shopinvader/documentation pull request #4
Opened 2019-07-18 16:30 UTC by thibaultrey

2019-07-18 16:36 UTC, thibaultrey commented
@pierrickbrun

2019-07-19 09:11 UTC, PierrickBrun requested changes

2019-07-19 09:11 UTC, PierrickBrun commented on data/doc_pages/en/cart.md
> +> **Selected_carrier** and **amount are** set only after call cart/apply_delivery_method API method
```suggestion
> **Selected_carrier** and **amount** are set only after call cart/apply_delivery_method API method
```

2019-07-19 09:11 UTC, PierrickBrun commented on data/doc_pages/en/cart.md
> +Line object have to nested attributes :
```suggestion
Line object have two nested attributes :
```

2019-07-19 09:11 UTC, PierrickBrun commented on data/doc_pages/en/cart.md
> +cart step is used to get cart feedback for marchant cart analysis. It's also used to transform a cart to an order after the checkout.
```suggestion
cart step is used to get cart feedback for marchant cart analysis. It's also used to transform a cart into an order after the checkout.
```

2019-07-19 09:11 UTC, PierrickBrun commented on data/doc_pages/en/cart.md
> +Set a shipping address is necessary to make API call on `cart/get_delivery_methods` to get carrier list.
```suggestion
Setting a shipping address is necessary to make API calls on `cart/get_delivery_methods` to get the carrier list. 
```

2019-07-19 09:11 UTC, PierrickBrun commented on data/doc_pages/en/cart.md
> +`invader_success_url` and `invader_error_url` params are used for HTTP redirection after submition according to the response state (valid or error).
```suggestion
`invader_success_url` and `invader_error_url` parameters are used for HTTP redirection after submission according to the response state (valid or error).
```

2019-07-19 09:11 UTC, PierrickBrun commented on data/doc_pages/en/cart.md
> +_To see how to call API method form HTML From See [Call API from HTML Form](./docs/api-call-in-form)._
```suggestion
_To see how to call API method from a HTML form See [Call API from HTML Form](./docs/api-call-in-form)._
```

2019-07-19 09:11 UTC, PierrickBrun commented on data/doc_pages/en/cart.md
> +Add product to cart. This method create a new line in cart and refresh `store.cart.lines` variable.
```suggestion
Add product to cart. This method creates a new line in the cart and refreshes the `store.cart.lines` variable.
```

2019-07-19 09:11 UTC, PierrickBrun commented on data/doc_pages/en/cart.md
> +This example is a form to set a shipping address in cart.
```suggestion
This example is a form to set a shipping address in the cart. 
```

2019-07-19 09:11 UTC, PierrickBrun commented on data/doc_pages/en/cart.md
> +Add new item in cart via simple HTML form.
```suggestion
Add a new item in the cart via a simple HTML form. 
```

2019-07-19 09:11 UTC, PierrickBrun commented on data/doc_pages/en/cart.md
> +This form add 10 product with ObjectID "123456" in the cart.
```suggestion
This form adds 10 products with ObjectID "123456" in the cart.
```

2019-07-19 09:11 UTC, PierrickBrun commented on data/doc_pages/en/cart.md
> +_To see how to call API method form HTML From See [Call API from HTML Form](./docs/api-call-in-form)._
```suggestion
_To see how to call API method from a HTML form See [Call API from HTML Form](./docs/api-call-in-form)._
```

2019-07-19 09:11 UTC, PierrickBrun commented on data/doc_pages/en/cart.md
> +Update cart line quantity.
```suggestion
Update a cart line quantity.
```

2019-07-19 09:11 UTC, PierrickBrun commented on data/doc_pages/en/cart.md
> +Add new item in cart via simple HTML form.
```suggestion
Add a new item in the cart via a simple HTML form. 
```

2019-07-19 09:11 UTC, PierrickBrun commented on data/doc_pages/en/cart.md
> +This form update line #1 to set quantity 8.
```suggestion
This form updates line #1 to set quantity = 8.
```

2019-07-19 09:11 UTC, PierrickBrun commented on data/doc_pages/en/cart.md
> +_To see how to call API method form HTML From See [Call API from HTML Form](./docs/api-call-in-form)._
```suggestion
_To see how to call API method from a HTML form See [Call API from HTML Form](./docs/api-call-in-form)._
```

2019-07-19 09:11 UTC, PierrickBrun commented on data/doc_pages/en/cart.md
> +Get the list of all delivery method available according to cart data (shipping area).
```suggestion
Get the list of all delivery methods available according to cart data (shipping area).
```

2019-07-19 09:11 UTC, PierrickBrun commented on data/doc_pages/en/cart.md
> +Set selected carrier on cart. This method causes shipping cost calculation depends on carrier, cart content and shipping area.
```suggestion
Set selected carrier on cart. This method causes shipping cost calculation depending on carrier, cart content and shipping area.
```

2019-07-19 09:11 UTC, PierrickBrun commented on data/doc_pages/en/cart.md
> +_To see how to call API method form HTML From See [Call API from HTML Form](./docs/api-call-in-form)._
```suggestion
_To see how to call API method from a HTML form See [Call API from HTML Form](./docs/api-call-in-form)._
```

2019-07-19 09:11 UTC, PierrickBrun commented on public/javascripts/document-menu.js
> +	/*
to delete

2019-07-19 09:22 UTC, merged